title: "SDDP release notes"
remote_theme: psrenergy/just-the-docs
logo: assets/images/psr_logo.png

psr_model: "SDDP"

toc:
  - title: Current version
    subfolderitems:
      - page: SDDP 18.0
        url: /sddp18.0
  - title: Previous versions
    subfolderitems:
      - title: SDDP 17.x
        subfolderitems:
          - page: SDDP 17.3
            url: /sddp17.3
          - page: SDDP 17.2
            url: /sddp17.2
          - page: SDDP 17.1
            url: /sddp17.1
          - page: SDDP 17.0
            url: /sddp17.0
      - page: SDDP 16.0
        url: /sddp16.0
      - page: SDDP 15.1
        url: /sddp15.1
      - page: SDDP 15.0
        url: /sddp15.0
      - page: SDDP 14.0
        url: /sddp14.0

#adding zoom in images
zoom_img_enabled: true

#dark/light mode
change_color_enabled: true
color_scheme: "dark"

url: "https://sddp-release-notes.psr-inc.com"

back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; <script>document.write(new Date().getFullYear())</script> PSR - <a href='https://www.psr-inc.com' target='_blank'>psr-inc.com</a>"
