title: "SDDP release notes"
remote_theme: psrenergy/just-the-docs
logo: assets/images/psr_logo.png

psr_model: "SDDP"

#adding zoom in images
zoom_img_enabled: true

#dark/light mode
change_color_enabled: true
color_scheme: "dark"

url: "https://docs.psr-inc.com/"

back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2023 PSR - <a href='https://www.psr-inc.com' target='_blank'>psr-inc.com</a>"
